---
- name: "Check for prometheus_msteams binary"
  ansible.builtin.stat:
    path: '{{ prometheus_msteams_install_dir }}/prometheus-msteams'
  changed_when: false
  register: prometheus_msteams_install

- name: "Install tasks"
  when: not prometheus_msteams_install.stat.exists or prometheus_msteams_force_install|bool
  block:
    - name: "Ensure install dir exists"
      ansible.builtin.file:
        path: '{{ item }}'
        state: directory
        mode: '0755'
      with_items:
        - "{{ prometheus_msteams_install_dir }}"
        - "{{ prometheus_msteams_config_dir }}"

    - name: "Install requierements"
      ansible.builtin.package:
        name: "ca-certificates"
        state: present

    - name: "Download prometheus_msteams..."
      ansible.builtin.get_url:
        url: '{{ prometheus_msteams_url }}'
        dest: '{{ prometheus_msteams_install_dir }}/prometheus-msteams'
        timeout: '60'
        mode: '0755'

- name: "Create systemd for prometheus_msteams"
  ansible.builtin.template:
    src: 'prometheus_msteams.service.j2'
    dest: '/etc/systemd/system/prometheus_msteams.service'
    mode: '0644'
  notify: "restart prometheus_msteams"

- name: "Create config file for connectors"
  ansible.builtin.template:
    src: 'connectors_config.yml.j2'
    dest: '{{ prometheus_msteams_config_dir }}/connectors_config.yml'
    mode: '0640'
  notify: "restart prometheus_msteams"

- name: "Copy message card"
  ansible.builtin.copy:
    src: 'message-card.tmpl'
    dest: '{{ prometheus_msteams_config_dir }}'
    mode: '0640'
  notify: "restart prometheus_msteams"

- name: "Start prometheus_msteams.service"
  ansible.builtin.service:
    name: prometheus_msteams
    state: started
    enabled: true
    daemon_reload: true
